[package]
name = "_2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
anyhow = "1.0.34"
fancy-regex = "0.4.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
